"""add paid_at to rewards

Revision ID: 52bdc65fb503
Revises: e6b1a56b15ef
Create Date: 2026-07-09 12:42:23.362747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bdc65fb503'
down_revision: Union[str, Sequence[str], None] = 'e6b1a56b15ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'paid_at')
    # ### end Alembic commands ###
