"""add violation_rules table

Revision ID: c98f93f77440
Revises: e6b1a56b15ef
Create Date: 2026-07-10 14:20:34.501808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98f93f77440'
down_revision: Union[str, Sequence[str], None] = 'e6b1a56b15ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=32), nullable=False),
    sa.Column('violation_type', sa.String(length=32), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('params', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_rules_rule_code'), 'violation_rules', ['rule_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_rules_rule_code'), table_name='violation_rules')
    op.drop_table('violation_rules')
    # ### end Alembic commands ###
